apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: weka
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/weka/kubectl-weka
  shortDescription: "Manage WEKA deployments in Kubernetes"
  description: |
    Kubectl plugin for WEKA operator and cluster planning, deployment, management and maintenance (status, preflight, logs, instances, support bundles).

  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/weka/kubectl-weka/releases/download/{{ .TagName }}/kubectl-weka_{{ .TagName }}_linux_amd64.tar.gz" .TagName | indent 6 }}
      bin: "kubectl-weka"

    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/weka/kubectl-weka/releases/download/{{ .TagName }}/kubectl-weka_{{ .TagName }}_linux_arm64.tar.gz" .TagName | indent 6 }}
      bin: "kubectl-weka"

    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/weka/kubectl-weka/releases/download/{{ .TagName }}/kubectl-weka_{{ .TagName }}_darwin_amd64.tar.gz" .TagName | indent 6 }}
      bin: "kubectl-weka"

    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/weka/kubectl-weka/releases/download/{{ .TagName }}/kubectl-weka_{{ .TagName }}_darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: "kubectl-weka"

    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/weka/kubectl-weka/releases/download/{{ .TagName }}/kubectl-weka_{{ .TagName }}_windows_amd64.zip" .TagName | indent 6 }}
      bin: "kubectl-weka.exe"

    - selector:
        matchLabels:
          os: windows
          arch: arm64
      {{addURIAndSha "https://github.com/weka/kubectl-weka/releases/download/{{ .TagName }}/kubectl-weka_{{ .TagName }}_windows_arm64.zip" .TagName | indent 6 }}
      bin: "kubectl-weka.exe"
