apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: longevity
  namespace: longevity
spec:
  cpuPolicy: auto
  driversDistService: https://10.240.200.5:14000
  dynamicTemplate:
    computeContainers: 4
    computeCores: 1
    driveContainers: 4
    driveCores: 1
    numDrives: 1
    nfsContainers: 2
    nfsCores: 1
    s3Cores: 1
    s3Containers: 1
    s3ExtraCores: 1

  gracefulDestroyDuration: 3s
  hotSpare: 0
  image: quay.io/weka.io/weka-in-container:4.4.10.200
  imagePullSecret: quay-io-robot-secret
  network:
    ethDevice: enp99s0f0np0
  nodeSelector:
    weka.io/dedicated: infra
  roleNodeSelector:
    s3:
      weka.io/dedicated: longevity

  template: dynamic
  rawTolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
